### ISSUE TITLE
[Android Bootcamp] Project 1: Instagram Client - Ready for Review

### ISSUE THREAD

**Issue by migaadi** [migaadi/InstagramClient#1]
My app is complete, please review. /cc @codepathreview @codepath

Also, I have a question about this one part where how do I make only the username bold while using same TextView for both username and caption? I tried using the HTML suggestion but it seems my usage is not correct. Thanks!

**Comment by nesquena** [comment]
:+1: Looks good overall. I have provided a detailed [Project 1 Feedback Guide here](http://courses.codepath.com/snippets/intro_to_android/project_1_feedback) which covers the most common issues with this submitted project. Read through the feedback guide point-by-point to determine how you could improve your submission. You should consider going back and implementing applicable feedback as well. Keep in mind that one of the most important parts of Android development is learning the correct patterns and conventions.

Hopefully this has given you a first sense of the RelativeLayout which is a very powerful layout system, probably one of the best responsive-first layout systems available across web and mobile platforms. This project also incorporates first introductions to basic networking, image loading and more complex feeds.

I would encourage you to also spend more time in future projects [improving the UI / UX](http://guides.codepath.com/android/Styling-UI-Screens-FAQ) as well by reviewing examples of [good UI design](http://www.android-app-patterns.com/).

**Comment by nesquena** [comment]
> Also, I have a question about this one part where how do I make only the username bold while using same TextView for both username and caption? I tried using the HTML suggestion but it seems my usage is not correct. Thanks!

See https://github.com/codepath/android_guides/wiki/Working-with-the-TextView#inserting-html-formatting

**Comment by migaadi** [comment]
I replaced following:
-        String formatted_username = "<b>" + photo.username + "</b>";
-        String username_caption = Html.fromHtml(formatted_username) + " -- " + photo.caption;

with this:
-        String formatted_username_caption = "<b>" + photo.username + "</b> -- " + photo.caption;
-        Spanned username_caption = Html.fromHtml(formatted_username_caption);

And now the username does show up as bold in the same TextView as caption. Thanks!
